/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:javascript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

/**
 * @typedef BaseEvent
 * @type {object}
 * @property {string} event_type
 * @property {Object.<string, *>} [event_properties]
 */

/**
 * @typedef Plan
 * @type {object}
 * @property {string} [branch]
 * @property {string} [source]
 * @property {string} [version]
 * @property {string} [versionId]
 */

/**
 * @typedef LoadClientOptions
 * @type {object}
 * @property {string} [apiKey]
 * @property {Object} [configuration]
 * @property {BrowserClient} [instance]
 */

/**
 * @typedef LoadOptions
 * @type {object}
 * @property {'goldemoamplicli'} [environment]
 * @property {boolean} [disabled]
 * @property {LoadClientOptions} [client]
 */

/**
 * @typedef {Object} EventOptions
 * @type {object}
 */

/**
 * @typedef ApiKey
 * @type {object}
 * @property {string} goldemoamplicli
 */
export const ApiKey = {
  goldemoamplicli: '96b31b4fd721e79dd7a29481d06c360e'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration = {
  plan: {
    version: '1',
    branch: 'import',
    source: 'web',
    versionId: 'cd579d7f-c2ad-465f-b7d3-bb0784ecdd16'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-javascript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export class BookingConfirmationViewed {
  constructor(properties) {
    this.event_type = 'Booking Confirmation Viewed';
    this.event_properties = properties;
  }
}

export class BookingDetailsConfirmed {
  constructor(properties) {
    this.event_type = 'Booking Details Confirmed';
    this.event_properties = properties;
  }
}

export class BookingReviewViewed {
  constructor(properties) {
    this.event_type = 'Booking Review Viewed';
    this.event_properties = properties;
  }
}

export class CheckoutStarted {
  constructor(properties) {
    this.event_type = 'Checkout Started';
    this.event_properties = properties;
  }
}

export class FareSelected {
  constructor(properties) {
    this.event_type = 'Fare Selected';
    this.event_properties = properties;
  }
}

export class FlightSearchFailed {
  constructor(properties) {
    this.event_type = 'Flight Search Failed';
    this.event_properties = properties;
  }
}

export class FlightSearchFilterApplied {
  constructor(properties) {
    this.event_type = 'Flight Search Filter Applied';
    this.event_properties = properties;
  }
}

export class FlightSearchResultsViewed {
  constructor(properties) {
    this.event_type = 'Flight Search Results Viewed';
    this.event_properties = properties;
  }
}

export class FlightSearchStarted {
  constructor(properties) {
    this.event_type = 'Flight Search Started';
    this.event_properties = properties;
  }
}

export class FlightSearchSubmitted {
  constructor(properties) {
    this.event_type = 'Flight Search Submitted';
    this.event_properties = properties;
  }
}

export class FlightSelected {
  constructor(properties) {
    this.event_type = 'Flight Selected';
    this.event_properties = properties;
  }
}

export class PassengerDetailsStarted {
  constructor(properties) {
    this.event_type = 'Passenger Details Started';
    this.event_properties = properties;
  }
}

export class PassengerDetailsSubmitted {
  constructor(properties) {
    this.event_type = 'Passenger Details Submitted';
    this.event_properties = properties;
  }
}

export class PassengerDetailsValidationFailed {
  constructor(properties) {
    this.event_type = 'Passenger Details Validation Failed';
    this.event_properties = properties;
  }
}

export class PaymentDetailsSubmitted {
  constructor(properties) {
    this.event_type = 'Payment Details Submitted';
    this.event_properties = properties;
  }
}

export class PaymentFailed {
  constructor(properties) {
    this.event_type = 'Payment Failed';
    this.event_properties = properties;
  }
}

export class PaymentMethodSelected {
  constructor(properties) {
    this.event_type = 'Payment Method Selected';
    this.event_properties = properties;
  }
}

export class PurchaseCompleted {
  constructor(properties) {
    this.event_type = 'Purchase Completed';
    this.event_properties = properties;
  }
}

export class ScreenViewed {
  constructor(properties) {
    this.event_type = 'Screen Viewed';
    this.event_properties = properties;
  }
}

export class TripSelectionCompleted {
  constructor(properties) {
    this.event_type = 'Trip Selection Completed';
    this.event_properties = properties;
  }
}

/**
 * @typedef PromiseResult
 * @type {object}
 * @property {Promise|undefined} promise
 */

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  constructor() {
    /* @type {BrowserClient|undefined} */
    this.amplitude = undefined;
    this.disabled = false;
  }

  /**
   * @return {BrowserClient}
   */
  get client() {
    this.isInitializedAndEnabled();
    return this.amplitude;
  }

  /**
   * @return {boolean}
   */
  get isLoaded() {
    return this.amplitude != null;
  }

  /**
   * @private
   * @return {boolean}
   */
  isInitializedAndEnabled() {
    if (!this.isLoaded) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param {LoadOptions} options Configuration options to initialize the Ampli SDK with. 'environment', 'client.apiKey' or 'client.instance' is required.
   *
   * @return {PromiseResult}
   */
  load(options) {
    this.disabled = options?.disabled ?? false;

    if (this.isLoaded) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey;
    if (options?.client?.apiKey) {
      apiKey = options.client.apiKey;
    } else if (options?.environment) {
      apiKey = ApiKey[options.environment];
    }

    if (options?.client?.instance) {
      this.amplitude = options?.client?.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user.
   *
   * @param {string|undefined} userId The user's id.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  identify(userId, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options, user_id: userId};
    }

    const ampIdentify = new amplitude.Identify();
    return this.amplitude.identify(ampIdentify, options);
  }

  /**
  * Flush the event.
  */
  flush() {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.flush();
  }

  /**
   * Track event
   *
   * @param {BaseEvent} event The event to track.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  track(event, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.track(event, undefined, options);
  }

  /**
   * Booking Confirmation Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Booking%20Confirmation%20Viewed)
   *
   * Disparado na visualizacao da tela de confirmacao da reserva.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {string} properties.booking_reference Localizador PNR
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  bookingConfirmationViewed(properties, options) {
    return this.track(new BookingConfirmationViewed(properties), options);
  }

  /**
   * Booking Details Confirmed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Booking%20Details%20Confirmed)
   *
   * Disparado na confirmacao dos detalhes da reserva pelo usuario.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {boolean} [properties.edited_before_confirm] Se o usuario voltou para editar algo antes de confirmar
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.total_amount Valor total da reserva
   * @param {EventOptions} [options] Options for this track call.
   */
  bookingDetailsConfirmed(properties, options) {
    return this.track(new BookingDetailsConfirmed(properties), options);
  }

  /**
   * Booking Review Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Booking%20Review%20Viewed)
   *
   * Disparado na visualizacao da tela de revisao da reserva.
   *
   * @param {Object} properties The event's properties.
   * @param {number} [properties.ancillaries_amount] Valor de servicos adicionais
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {number} properties.base_fare_amount Valor da tarifa base
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.taxes_amount Valor de taxas
   * @param {number} properties.total_amount Valor total da reserva
   * @param {EventOptions} [options] Options for this track call.
   */
  bookingReviewViewed(properties, options) {
    return this.track(new BookingReviewViewed(properties), options);
  }

  /**
   * Checkout Started
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Checkout%20Started)
   *
   * Disparado no momento em que o booking_id e gerado, iniciando o checkout.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id UUID gerado no cliente, correlaciona os eventos do checkout
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} properties.passenger_total_count Quantidade total de passageiros
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {number} properties.total_amount Valor total da reserva
   * @param {'one_way'|'round_trip'} properties.trip_type Tipo de viagem
   * @param {EventOptions} [options] Options for this track call.
   */
  checkoutStarted(properties, options) {
    return this.track(new CheckoutStarted(properties), options);
  }

  /**
   * Fare Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Fare%20Selected)
   *
   * Disparado quando o usuario escolhe a familia tarifaria de um trecho.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {'light'|'plus'|'top'} properties.fare_family Familia tarifaria escolhida
   * @param {'outbound'|'inbound'} properties.leg_type Trecho da tarifa selecionada
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.price_amount Preco da tarifa selecionada
   * @param {number} [properties.price_difference_from_lowest] Diferenca de preco em relacao a tarifa mais barata
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {EventOptions} [options] Options for this track call.
   */
  fareSelected(properties, options) {
    return this.track(new FareSelected(properties), options);
  }

  /**
   * Flight Search Failed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Search%20Failed)
   *
   * Disparado quando a busca de voos falha ou nao retorna resultados.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} [properties.error_code] Codigo interno do erro
   * @param {'no_results'|'invalid_route'|'timeout'|'unexpected_error'} properties.error_type Tipo de erro ocorrido na busca
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSearchFailed(properties, options) {
    return this.track(new FlightSearchFailed(properties), options);
  }

  /**
   * Flight Search Filter Applied
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Search%20Filter%20Applied)
   *
   * Disparado quando o usuario aplica um filtro ou ordenacao sobre os resultados.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {'stops'|'departure_time'|'duration'|'airline'|'price'} properties.filter_type Tipo de filtro aplicado
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.result_count_after Quantidade de resultados apos o filtro
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {'price_asc'|'duration_asc'|'departure_asc'|'recommended'} [properties.sort_type] Tipo de ordenacao aplicada
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSearchFilterApplied(properties, options) {
    return this.track(new FlightSearchFilterApplied(properties), options);
  }

  /**
   * Flight Search Results Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Search%20Results%20Viewed)
   *
   * Disparado quando os resultados da busca sao exibidos ao usuario.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'BRL'} properties.currency Moeda dos valores exibidos
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {boolean} properties.has_results Se a busca retornou algum resultado
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} [properties.lowest_price_amount] Menor preco encontrado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.result_count Quantidade de resultados retornados
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {number} properties.search_latency_ms Latencia da busca em milissegundos
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSearchResultsViewed(properties, options) {
    return this.track(new FlightSearchResultsViewed(properties), options);
  }

  /**
   * Flight Search Started
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Search%20Started)
   *
   * Disparado quando o usuario interage pela primeira vez com o formulario de busca.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'home'|'results_edit'|'deeplink'} properties.entry_point Ponto de entrada que originou a busca
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSearchStarted(properties, options) {
    return this.track(new FlightSearchStarted(properties), options);
  }

  /**
   * Flight Search Submitted
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Search%20Submitted)
   *
   * Disparado no envio do formulario de busca, antes da resposta da camada mockada.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'economy'|'premium_economy'|'business'} properties.cabin_class Classe de cabine buscada
   * @param {number} properties.days_to_departure Dias ate a partida
   * @param {string} properties.departure_date Data de ida, formato YYYY-MM-DD
   * @param {string} properties.destination_iata Codigo IATA de destino
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {boolean} properties.is_domestic Se a busca e um voo domestico
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {string} properties.origin_iata Codigo IATA de origem
   * @param {number} properties.passenger_adult_count Quantidade de passageiros adultos
   * @param {number} properties.passenger_child_count Quantidade de passageiros criancas
   * @param {number} properties.passenger_infant_count Quantidade de passageiros bebes
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {string} [properties.return_date] Data de volta, formato YYYY-MM-DD
   * @param {string} properties.search_id UUID gerado no cliente, correlaciona os eventos da busca
   * @param {number} [properties.trip_length_days] Duracao da viagem em dias
   * @param {'one_way'|'round_trip'} properties.trip_type Tipo de viagem
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSearchSubmitted(properties, options) {
    return this.track(new FlightSearchSubmitted(properties), options);
  }

  /**
   * Flight Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Flight%20Selected)
   *
   * Disparado a cada trecho selecionado. Em ida e volta, ocorre duas vezes.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.carrier_code Codigo da companhia aerea
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {number} properties.departure_hour Hora de partida (0-23)
   * @param {number} properties.duration_minutes Duracao do trecho em minutos
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.flight_number Numero do voo (ex: AM1234)
   * @param {boolean} properties.is_direct Se o voo e direto, sem escalas
   * @param {'outbound'|'inbound'} properties.leg_type Trecho selecionado
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.price_amount Preco do trecho selecionado
   * @param {number} properties.result_position Posicao do voo na lista de resultados
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {number} properties.stops_count Quantidade de escalas
   * @param {EventOptions} [options] Options for this track call.
   */
  flightSelected(properties, options) {
    return this.track(new FlightSelected(properties), options);
  }

  /**
   * Passenger Details Started
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Passenger%20Details%20Started)
   *
   * Disparado quando o usuario inicia o preenchimento dos dados dos passageiros.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} properties.passenger_total_count Quantidade total de passageiros
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  passengerDetailsStarted(properties, options) {
    return this.track(new PassengerDetailsStarted(properties), options);
  }

  /**
   * Passenger Details Submitted
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Passenger%20Details%20Submitted)
   *
   * Envio dos dados de passageiro. Nenhum dado pessoal e enviado, apenas metadados de preenchimento.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'cpf'|'passport'|'rg'} properties.document_type Tipo de documento informado
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {boolean} properties.has_infant Se ha bebe entre os passageiros
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} properties.passenger_total_count Quantidade total de passageiros
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} [properties.time_to_complete_seconds] Tempo gasto no preenchimento, em segundos
   * @param {boolean} [properties.used_autofill] Se o usuario utilizou autopreenchimento
   * @param {EventOptions} [options] Options for this track call.
   */
  passengerDetailsSubmitted(properties, options) {
    return this.track(new PassengerDetailsSubmitted(properties), options);
  }

  /**
   * Passenger Details Validation Failed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Passenger%20Details%20Validation%20Failed)
   *
   * Disparado quando a validacao dos dados do passageiro falha.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {number} properties.attempt_count Numero de tentativas de preenchimento
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {'required'|'invalid_format'|'underage'|'document_mismatch'} properties.error_type Tipo de erro de validacao
   * @param {'first_name'|'last_name'|'birth_date'|'document_number'|'email'|'phone'} properties.field_name Campo que falhou na validacao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  passengerDetailsValidationFailed(properties, options) {
    return this.track(new PassengerDetailsValidationFailed(properties), options);
  }

  /**
   * Payment Details Submitted
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Payment%20Details%20Submitted)
   *
   * Envio dos dados de pagamento. Nenhum dado de cartao e enviado.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'visa'|'mastercard'|'elo'|'amex'|'hipercard'} [properties.card_brand] Bandeira do cartao, quando aplicavel
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {number} [properties.installment_count] Numero de parcelas
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'credit_card'|'pix'|'miles'|'miles_plus_money'|'boleto'} properties.payment_method Metodo de pagamento utilizado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.total_amount Valor total pago
   * @param {EventOptions} [options] Options for this track call.
   */
  paymentDetailsSubmitted(properties, options) {
    return this.track(new PaymentDetailsSubmitted(properties), options);
  }

  /**
   * Payment Failed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Payment%20Failed)
   *
   * Disparado a partir da resposta da camada mockada quando o pagamento falha, nunca de forma otimista.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {number} properties.attempt_count Numero de tentativas de pagamento
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {'insufficient_funds'|'card_declined'|'invalid_card'|'gateway_timeout'|'fraud_suspicion'} properties.failure_reason Motivo da falha de pagamento
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'credit_card'|'pix'|'miles'|'miles_plus_money'|'boleto'} properties.payment_method Metodo de pagamento utilizado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.total_amount Valor total da tentativa de pagamento
   * @param {EventOptions} [options] Options for this track call.
   */
  paymentFailed(properties, options) {
    return this.track(new PaymentFailed(properties), options);
  }

  /**
   * Payment Method Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Payment%20Method%20Selected)
   *
   * Disparado na selecao do metodo de pagamento.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {boolean} [properties.has_interest] Se o parcelamento tem juros
   * @param {number} [properties.installment_count] Numero de parcelas
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} [properties.miles_used_count] Quantidade de milhas utilizadas
   * @param {'credit_card'|'pix'|'miles'|'miles_plus_money'|'boleto'} properties.payment_method Metodo de pagamento selecionado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  paymentMethodSelected(properties, options) {
    return this.track(new PaymentMethodSelected(properties), options);
  }

  /**
   * Purchase Completed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Purchase%20Completed)
   *
   * Unico evento autorizado a carregar receita. Disparado apenas apos resposta positiva da camada mockada, com insert_id deterministico.
   *
   * @param {Object} properties The event's properties.
   * @param {number} [properties.ancillaries_amount] Valor de servicos adicionais
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {number} properties.base_fare_amount Valor da tarifa base
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {string} properties.booking_reference Localizador PNR
   * @param {'economy'|'premium_economy'|'business'} properties.cabin_class Classe de cabine comprada
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {number} properties.days_to_departure Dias ate a partida
   * @param {string} properties.destination_iata Codigo IATA de destino
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {'light'|'plus'|'top'} properties.fare_family Familia tarifaria comprada
   * @param {number} [properties.installment_count] Numero de parcelas
   * @param {boolean} properties.is_domestic Se o voo e domestico
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {string} properties.order_id UUID da compra
   * @param {string} properties.origin_iata Codigo IATA de origem
   * @param {number} properties.passenger_total_count Quantidade total de passageiros
   * @param {'credit_card'|'pix'|'miles'|'miles_plus_money'|'boleto'} properties.payment_method Metodo de pagamento utilizado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {number} properties.revenue Campo nativo de receita do Amplitude
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {number} properties.taxes_amount Valor de taxas
   * @param {number} [properties.time_to_purchase_seconds] Tempo da busca ate a compra, em segundos
   * @param {'one_way'|'round_trip'} properties.trip_type Tipo de viagem
   * @param {EventOptions} [options] Options for this track call.
   */
  purchaseCompleted(properties, options) {
    return this.track(new PurchaseCompleted(properties), options);
  }

  /**
   * Screen Viewed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Screen%20Viewed)
   *
   * Visualizacao de pagina/tela. Evento transversal disparado em toda navegacao entre telas.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'search'|'select'|'passenger'|'review'|'payment'|'confirmation'} [properties.booking_step] Etapa do funil de reserva correspondente a tela
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {string} [properties.referrer_screen] Tela de origem da navegacao
   * @param {'home'|'search_results'|'flight_selection'|'passenger_details'|'booking_review'|'payment'|'confirmation'} properties.screen_name Identificador da tela visualizada
   * @param {EventOptions} [options] Options for this track call.
   */
  screenViewed(properties, options) {
    return this.track(new ScreenViewed(properties), options);
  }

  /**
   * Trip Selection Completed
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Trip%20Selection%20Completed)
   *
   * Disparado quando todos os trechos e tarifas necessarios foram escolhidos.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {'BRL'} properties.currency Moeda do valor
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {string} properties.search_id Correlaciona com a busca original
   * @param {number} [properties.time_to_select_seconds] Tempo gasto para concluir a selecao, em segundos
   * @param {number} properties.total_amount Valor total da viagem selecionada
   * @param {'one_way'|'round_trip'} properties.trip_type Tipo de viagem
   * @param {EventOptions} [options] Options for this track call.
   */
  tripSelectionCompleted(properties, options) {
    return this.track(new TripSelectionCompleted(properties), options);
  }
}

export const ampli = new Ampli();
