/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 2
 * Build: 1.0.0
 * Runtime: browser:javascript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

/**
 * @typedef BaseEvent
 * @type {object}
 * @property {string} event_type
 * @property {Object.<string, *>} [event_properties]
 */

/**
 * @typedef Plan
 * @type {object}
 * @property {string} [branch]
 * @property {string} [source]
 * @property {string} [version]
 * @property {string} [versionId]
 */

/**
 * @typedef LoadClientOptions
 * @type {object}
 * @property {string} [apiKey]
 * @property {Object} [configuration]
 * @property {BrowserClient} [instance]
 */

/**
 * @typedef LoadOptions
 * @type {object}
 * @property {'goldemoamplicli'} [environment]
 * @property {boolean} [disabled]
 * @property {LoadClientOptions} [client]
 */

/**
 * @typedef {Object} EventOptions
 * @type {object}
 */

/**
 * @typedef ApiKey
 * @type {object}
 * @property {string} goldemoamplicli
 */
export const ApiKey = {
  goldemoamplicli: '96b31b4fd721e79dd7a29481d06c360e'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration = {
  plan: {
    version: '2',
    branch: 'import',
    source: 'web',
    versionId: '4a25e1b7-3bf1-43bf-92c1-0a43c7ae23c9'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-javascript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export class Identify {
  constructor(properties) {
    this.event_type = amplitude.Types.SpecialEventType.IDENTIFY;
    this.event_properties = properties;
  }
}

export class LogoHomeClicked {
  constructor() {
    this.event_type = 'Logo Home Clicked';
  }
}

export class PaymentMethodSelected {
  constructor(properties) {
    this.event_type = 'Payment Method Selected';
    this.event_properties = properties;
  }
}

/**
 * @typedef PromiseResult
 * @type {object}
 * @property {Promise|undefined} promise
 */

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  constructor() {
    /* @type {BrowserClient|undefined} */
    this.amplitude = undefined;
    this.disabled = false;
  }

  /**
   * @return {BrowserClient}
   */
  get client() {
    this.isInitializedAndEnabled();
    return this.amplitude;
  }

  /**
   * @return {boolean}
   */
  get isLoaded() {
    return this.amplitude != null;
  }

  /**
   * @private
   * @return {boolean}
   */
  isInitializedAndEnabled() {
    if (!this.isLoaded) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param {LoadOptions} options Configuration options to initialize the Ampli SDK with. 'environment', 'client.apiKey' or 'client.instance' is required.
   *
   * @return {PromiseResult}
   */
  load(options) {
    this.disabled = options?.disabled ?? false;

    if (this.isLoaded) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey;
    if (options?.client?.apiKey) {
      apiKey = options.client.apiKey;
    } else if (options?.environment) {
      apiKey = ApiKey[options.environment];
    }

    if (options?.client?.instance) {
      this.amplitude = options?.client?.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set or update that user's properties.
   *
   * @param {string|undefined} userId The user's id.
   * @param {Object} [properties] The user's properties.
   * @param {string} [properties.first_search_date] Data da primeira busca registrada
   * @param {boolean} [properties.is_logged_in] Usuario autenticado
   * @param {'none'|'silver'|'gold'|'diamond'} [properties.loyalty_tier] Nivel no programa de fidelidade
   * @param {'economy'|'premium_economy'|'business'} [properties.preferred_cabin] Cabine mais frequentemente escolhida
   * @param {'app'|'web'|'partner'} [properties.signup_channel] Canal de origem do cadastro
   * @param {number} [properties.total_bookings_count] Reservas concluidas historicamente
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  identify(userId, properties, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options, user_id: userId};
    }

    const ampIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        ampIdentify.set(key, value);
      }
    }
    return this.amplitude.identify(ampIdentify, options);
  }

  /**
  * Flush the event.
  */
  flush() {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.flush();
  }

  /**
   * Track event
   *
   * @param {BaseEvent} event The event to track.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  track(event, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.track(event, undefined, options);
  }

  /**
   * Logo Home Clicked
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Logo%20Home%20Clicked)
   *
   * Disparado quando o usuário clica no logo da Hoome
   *
   *
   *
   *
   * @param {EventOptions} [options] Options for this track call.
   */
  logoHomeClicked(options) {
    return this.track(new LogoHomeClicked(), options);
  }

  /**
   * Payment Method Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/productminds/Gol%20Demo%20-%20Ampli%20CLI/events/import/latest/Payment%20Method%20Selected)
   *
   * Disparado na selecao do metodo de pagamento.
   *
   * @param {Object} properties The event's properties.
   * @param {string} properties.app_version Versao da aplicacao (semver)
   * @param {string} properties.booking_id Correlaciona com o checkout
   * @param {'development'|'staging'|'production'} properties.environment Ambiente de execucao
   * @param {boolean} [properties.has_interest] Se o parcelamento tem juros
   * @param {number} [properties.installment_count] Numero de parcelas
   * @param {string} properties.locale Locale do usuario (ex: pt-BR)
   * @param {number} [properties.miles_used_count] Quantidade de milhas utilizadas
   * @param {'credit_card'|'pix'|'miles'|'miles_plus_money'|'boleto'} properties.payment_method Metodo de pagamento selecionado
   * @param {'ios'|'android'|'web'} properties.platform Plataforma de origem do evento
   * @param {EventOptions} [options] Options for this track call.
   */
  paymentMethodSelected(properties, options) {
    return this.track(new PaymentMethodSelected(properties), options);
  }
}

export const ampli = new Ampli();
